### ISSUE TITLE
Dircovery rule Public Endpoints Optimize

### ISSUE THREAD

**Issue by galoxucro** [gerardlemetayerc/zabbix-microsoft365-monitoring#12]
It seems to me that there are two discovery rules named "_Microsoft365 - Public Endpoints - Discovery - TCP - Required - Allow_".

![image](https://github.com/gerardlemetayerc/zabbix-microsoft365-monitoring/assets/18370988/041b5961-f1a4-4827-a3a2-268d5e98dba3)

I think one of them should be named something like "_Microsoft365 - Public Endpoints - Discovery - TCP - Required - **Optimize**_".

**Comment by gerardlemetayerc** [comment]
I've noticed this point one week ago, I need to review this discovery. :)
