### ISSUE TITLE
Create v6.0.0 template

### ISSUE THREAD

**Issue by gerardlemetayerc** [gerardlemetayerc/zabbix-microsoft365-monitoring#6]
Current template is only valid for v6.4.0. should be better to export configuration from v6.0.0 (or check how to adapt v6.4.0 to v6.0.0)

**Comment by galoxucro** [comment]
1- Edit the .yaml file and:
  1.1- edit tag 'version:'  6.4  -> 6.0 
  1.2- remove the sections 'template_groups:' and 'vendor:'
2- Save the file
3- Import in Zabbix 6.0

**Comment by gerardlemetayerc** [comment]
Thanks! I will test it for the next commit.
