### ISSUE TITLE
Division by 0 on 'Percent used'

### ISSUE THREAD

**Issue by galoxucro** [gerardlemetayerc/zabbix-microsoft365-monitoring#9]
Sometimes you're using some licenses but you have them no more:

![image](https://user-images.githubusercontent.com/18370988/236297592-148afd8b-2b96-46f4-9d2a-60108674d911.png)

There shoud be some check to avoid division by zero, or even a trigger to alert an unlicensed product in use.

**Comment by galoxucro** [comment]
This is another case os division/0 that should be treated (perhaps excluding from discovery?).
![image](https://user-images.githubusercontent.com/18370988/236314049-ff381454-7634-4ea8-8524-6706943287e9.png)

**Comment by gerardlemetayerc** [comment]
Hello, Indeed I've not seen it coming... Thanks for the feedback.

There's a tricky workaround for this, I will test it in the next days and push it if it's work.

**Comment by gerardlemetayerc** [comment]
Issue should be now solved by this applied workaround.
